### ISSUE TITLE
Connect-BPAServer does not work with Automate Enterprise 11

### ISSUE THREAD

**Issue by TommiieeSV** [davidseibel/PoshBPA#33]
## Expected Behavior
Connect to Automate Enterprise 11 server.

## Actual Behavior
```
Failed to connect to BPA server <server name>:9608!
At C:\Program Files\WindowsPowerShell\Modules\PoshBPA\2.3.0\Scripts\Connect-BPAServer.ps1:103 char:13
+             throw "Failed to connect to BPA server $($server):$($Port ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to conne...<server name>:9608!:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to connect to BPA server <server name>:9608!
```

## Steps to Reproduce the Problem
Use Connect-BPAServer in combination with Automate Enterprise 11.

## Specifications

  - PoshBPA Version: 2.3.0
  - PowerShell Version: 5.0
  - AutoMate Enterprise Version: 11.0.6.12

## Extra
The port used in Connect-BPAServer (9608) is not the right one for Automate 11. It should be 9708. But even then, the same error occurs. I've investigated the Connect-BPAServer module and from what I can tell it doesn't pass on any authentication to the Automate API.

I can connect to the Automate API successfully with this snippet:
```
$pw = [System.Text.Encoding]::UTF8.GetBytes("<username>:<password>")
$base64 = [System.Convert]::ToBase64String($pw)
$headers = @{"Authorization"= "Basic $base64"}
$request = "http://<bpaserver>:9708/BPAManagement/info/get"
$response = Invoke-RestMethod $request -Headers $headers -Method GET
```

**Comment by davidseibel** [comment]
I tested against v11 and don't have this issue (albeit against a different version).  Here's what I ran:
```PowerShell
Connect-BPAServer <servername> -Port 9708 -Credential (Get-Credential)
```

The "info/get" method doesn't require authentication, but all other methods do.  The first thing Connect-BPAServer does is test that it can communicate with the server (without auth).  If it can, it creates the global $BPAConnectionInfo variable that contains the connection/auth information used by the rest of the module and tests authentication against "users/authenticate".  The authentication logic you tested does exist in the module, but it's in Invoke-BPARestMethod, not Connect-BPAServer.

Can you test running just this for me?

``` PowerShell
Invoke-RestMethod "http://<server>:<port>/BPAManagement/info/get" -Method Get
```

It should throw a more useful error, please post back here if you don't mind.  Connect-BPAServer discards this error and throws the generic error that you see.  Maybe I should include the original error - could be a possible enhancement.

**Comment by TommiieeSV** [comment]
Hi,

I discovered what went wrong. For some reason I had to use the FQDN of the server instead of just the hostname. Using the FQDN I have no trouble connecting PoshBPA to Automate 11.

Apologies for the inconvenience.
